# I/O
input_filename: "data/SRF_Input_Base_V4.csv"
output_directory: "data/output" # THIS DIRECTORY IS EMPTIED EACH TIME THE MODEL IS RUN

# Filtering
single_family_target_vacancy_rate: 0.06 # all vacancy rates in %
multi_family_target_vacancy_rate: 0.06
industrial_target_vacancy_rate: 0.06
commercial_target_vacancy_rate: 0.06
office_target_vacancy_rate: 0.06
non_residential_target_vacancy_rate: 0.1 # from SLC Model
minimum_redevelopment_age: 20
profit_multiplier: 1.25 # used to calculate minimum acceptable profit margin
amortization_years: 20

# Simulation
simulation_years: 5
simulation_begin: 2020

# Sizes - all sizes in square feet
single_family_minimum_unit_size: 800 # from SLC Model
multi_family_minimum_unit_size: 800 # from SLC Model

residential_square_feet_per_job: 400 # from SLC Model
non_residential_square_feet_per_job: 600 # from SLC Model
industrial_square_feet_per_job: 648 # from SLC Model
commercial_square_feet_per_job: 650 # from SLC Model
office_square_feet_per_job: 462 # from SLC Model

# Construction Cost/Square Foot by product type
# Proposed by SANDAG based on this source: https://ccorpinsights.com/costs-per-square-foot/
office_construction_cost: 379.5
commercial_construction_cost: 228.5
industrial_construction_cost: 261.5
multi_family_construction_cost: 192.5
single_family_construction_cost: 388

# Demand
industrial_units_per_year: 4000
office_units_per_year: 4000
commercial_units_per_year: 4000

single_family_units_per_year: 5000
multi_family_units_per_year: 5000

# set to 1 for verbose output
debug: 0
