# I/O
input_filename: "data/SRF_Input_Base_V1_060820.csv"
output_directory: "data/output" # THIS DIRECTORY IS EMPTIED EACH TIME THE MODEL IS RUN

# Filtering
target_vacancy_rate: 0.06

non_residential_target_vacancy_rate: 0.1 # from SLC Model
minimum_redevelopment_age: 20

# Simulation
simulation_years: 5
simulation_begin: 2020

# Sizes - all sizes in square feet
single_family_minimum_unit_size: 800 # from SLC Model
multi_family_minimum_unit_size: 800 # from SLC Model

residential_square_feet_per_job: 400 # from SLC Model
non_residential_square_feet_per_job: 600 # from SLC Model
industrial_square_feet_per_job: 648 # from SLC Model
commercial_square_feet_per_job: 650 # from SLC Model
office_square_feet_per_job: 462 # from SLC Model

# Construction Cost/Square Foot by product type
# Proposed by SANDAG based on this source: https://ccorpinsights.com/costs-per-square-foot/
office_construction_cost: 379.5
retail_construction_cost: 228.5
industrial_construction_cost: 261.5
multi_family_construction_cost: 192.5
single_family_construction_cost: 388

# Demand
new_units_industrial: 4000
new_units_office: 4000
new_units_commercial: 4000

new_units_single_family: 5000
new_units_multi_family: 5000

# 1 for printing frames
debug: 0
